USE AIRWAY_BOOKING;

ALTER TABLE PAYMENT_ACCOUNT
ADD CONSTRAINT PAYMENT_ACCOUNT_expire_date_ck
CHECK (expire_date > GETDATE());

ALTER TABLE BOOKING
ADD CONSTRAINT BOOKING_discount_ck
CHECK (discount<10);

ALTER TABLE PASSENGER_INFO
ADD CONSTRAINT PASSENGER_INFO_email_uq
UNIQUE(email);



